### ISSUE TITLE
support for node environments

### ISSUE THREAD

**Issue by svanzoest** [chicoxyzzy/node-releases#1]
this maybe off topic, but it would be neat to have node environments supported similar to browsers, but rather for cloud environments that use different versions of node. I am not sure if this overkill or a real thing, but figured I would at least bring it up.

I am thinking places such as: 
* AWS Lambda ([currently v4.3.2](http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html))
* Google Cloud Functions ([currently v6.9.1](https://cloud.google.com/functions/docs/writing/))
* IBM OpenWisk ([currently v6.9.1](https://console.ng.bluemix.net/docs/openwhisk/openwhisk_reference.html))
* Azure Functions ([currently v5.9.1](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node))

**Comment by iamstarkov** [comment]
what do you mean?

**Comment by iamstarkov** [comment]
sorry, i just didnt get what you want to have in the end

**Comment by svanzoest** [comment]
knowing which version of node release is on each platform is useful for things like babel to be able to specify something along the lines of needs support on azure and aws and have it do the right thing based on this data.

**Comment by chicoxyzzy** [comment]
It looks like a task for libs which will use data from this repo

**Comment by iamstarkov** [comment]
so, no work is required for node-releases, right?

**Comment by chicoxyzzy** [comment]
@iamstarkov yes I think so.
