### ISSUE TITLE
cannot install on npm

### ISSUE THREAD

**Issue by Symboler** [chicoxyzzy/node-releases#10]
![image](https://user-images.githubusercontent.com/33592051/58303597-7e558600-7e23-11e9-933c-d722e7f532a4.png)
npm install --save node-releases ,then throw the error

**Comment by laomu1988** [comment]
fail when use `npm install node-releases@1.1.21`
success when use `npm install node-releases@1.1.20`

**Comment by chicoxyzzy** [comment]
Sorry for long response. Do you have any issues with latest published versions?

**Comment by chicoxyzzy** [comment]
It seems that everything works now. I'll close this issue. Feel free to reopen if you think the issue is not solved.
