### ISSUE TITLE
Add the ChakraCore releases

### ISSUE THREAD

**Issue by nschonni** [chicoxyzzy/node-releases#15]
The are stored outside the main download directory in https://nodejs.org/download/chakracore-release/
This release-line is also halted AFAIK, but I guess it's the same case for the iojs one now too.

**Comment by chicoxyzzy** [comment]
@ai what do you think about adding Node ChakraCore data? Would it be useful for Browserslist?

**Comment by ai** [comment]
I afraid ChakraCore is dead after moving Edge to Chromium

**Comment by chicoxyzzy** [comment]
It's not dead, last release was 7 days ago. MSFT uses it in Azure and some other places. Though, Node ChakraCore seems to be unmaintained. Anyway it could be useful to have historical data.

**Comment by chicoxyzzy** [comment]
There are no plans to add ChakraCore builds anymore
