### ISSUE TITLE
Node 13.10.1 missing from env.json

### ISSUE THREAD

**Issue by nschonni** [chicoxyzzy/node-releases#20]
Looks like the process isn't grabbing the latest patch, and still has 13.10.0 in the env.json
Is the idea of the env.json contains just the latest patch version for each Major.Minor, or is there some other issue i'm hitting?

**Comment by chicoxyzzy** [comment]
Thank you for raising this topic. As far as I remember, the reasoning behind dropping patch versions was that for babel-preset-env we need only Node.js to V8 versions relation. In fact we may want to have patch versions also.

Do you think that patch versions could be useful in `env.json`?

cc @nicolo-ribaudo who can also have opinion on this :)

**Comment by nicolo-ribaudo** [comment]
`@babel/preset-env` only needs to be aware of v8 updates, but surely having patch releases wouldn't be a problem for us.

We wouldn't use them, but I can't think of a reason to not include them.

**Comment by nschonni** [comment]
OK, that's fine then. I wasn't following what the evn.json was besides a merged list of the node+iojs data. I'm going to close this one, since I'd probably just use the nodejs.json for the full list then.
