### ISSUE TITLE
Publish updated data containing the Node.js v16 release

### ISSUE THREAD

**Issue by jaydenseric** [chicoxyzzy/node-releases#26]
It's been a few days since the Node.js v16 release, yet the updated data hasn't been published:

https://unpkg.com/node-releases/data/processed/envs.json

**Comment by nschonni** [comment]
It did get added by the sync https://github.com/chicoxyzzy/node-releases/commit/ec56225605fa87f59f269c31892e45c2f1d081a2

**Comment by chicoxyzzy** [comment]
Node v16 is in the data now. Thanks for your observations!
