### ISSUE TITLE
Implement automatic data updates

### ISSUE THREAD

**Issue by chicoxyzzy** [chicoxyzzy/node-releases#3]
Idea: implement bot which will create new PR for review based on information from [CI daily cron job](https://docs.travis-ci.com/user/cron-jobs/). Not sure if it's possible. We should check. Other ideas are welcome.

**Comment by ai** [comment]
We have a bot on Digital Ocean to auto-release caniuse-lite

**Comment by ai** [comment]
Digital Ocean can give you a free server for open source

**Comment by chicoxyzzy** [comment]
Ok, we have GitHub actions now. I'll try to find some time to set up automatic updates, though I still appreciate any help.

**Comment by ad-m** [comment]
We can use https://github.com/ad-m/github-push-action to push changes to repository.

We need wrote single step to update data and connect it together in single workflow file.
