### ISSUE TITLE
Include extra fields

### ISSUE THREAD

**Issue by piranna** [chicoxyzzy/node-releases#34]
Add extra info from `allVersions.json` file when fetching it, specifically `v8` version.

**Comment by chicoxyzzy** [comment]
What is `allVersions.json`?

**Comment by chicoxyzzy** [comment]
There's a v8 version in 'https://nodejs.org/dist/index.json`. We can add it if necessary, not sure about other fields. `files` will add a lot of info which usually not necessary and only adds to the bundle's overall size.

**Comment by piranna** [comment]
Just v8 field is enough for me :-) At this moment i'm downloading the index.json file and parsing it, but make it imposible to use offline or on bad networks, that's why I would prefer to have it in a package.
