### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [chicoxyzzy/node-releases#4]
Hello :)

Could you please add a LICENSE file to the project?

**Comment by ai** [comment]
They have CC-BY 4 in package.json. I think it is ok, since there is no rules hope you should specify the last license.

**Comment by Bosch-Eli-Black** [comment]
Hi @ai,

I think that may not be enough to legally license the code under that license. My understanding is that a lot of licenses require you to include the full text of the license (or at least that's what people seem to be doing).

`babel`, for example, recently went through something similar, and they ended up including a LICENSE file in their project: https://github.com/babel/babel/pull/7308#issuecomment-367615152

**Comment by ai** [comment]
Yeap, I agree that it is better just to include text.

**Comment by chicoxyzzy** [comment]
Fixed
