### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by chicoxyzzy** [chicoxyzzy/node-releases#8]
I believe that I took CC license from somewhere on nodejs.org. Does this license fits well for Browserslist and other libraries and software which use node-releases/browserslist? I'm not an expert in this.

cc @ai

**Comment by chicoxyzzy** [comment]
Also we should consider that license change is probably a breaking change

**Comment by ai** [comment]
Yeap, CC-BY is very similar to MIT license and perfectly fit any other open source project (it is more liberal than GPL or CC-BY-SA)

**Comment by gyehuda** [comment]
I run into this a lot, sorry for chiming in from left field. MIT is a fantastic license for Node projects, most projects use it. CC-BY is philosophically similar ( _use this freely, just give me credit_ ), but it's better for static content (documentation, pictures, music) but not for code. MIT is better for code. I'll be glad to share details if you wish.

**Comment by chicoxyzzy** [comment]
What about JSON files?

**Comment by gyehuda** [comment]
I consider JSON files to be more like code. I agree it gets a little murky. CC-BY is a fine license (especially the 4.0 version). But my experience is that when you license node projects under MIT, people just use the code but when you use anything else people talk about the license.

**Comment by chicoxyzzy** [comment]
Makes sense. I thought about same issues. WDYT @ai? License change would be a breaking change in that case. Should we ask someone from Node core team maybe?

**Comment by ai** [comment]
Yeap, MIT license will reduce questions from people, who does not understand licenses.

I think JSON is not a code. But taking MIT is OK.

> Should we ask someone from Node core team maybe?

If you copy files or exact text. Date (versions, release dates) is not part of copyright.

But you could to ping them about this project.

> License change would be a breaking change in that case.

I do not think so. MIT and CC-BY will not change anything for users. So “public API” will not be changed.

**Comment by hyandell** [comment]
+1 from the bleachers. MIT also moves you from Category-It's-Complicated to Category-A-for-Apache-like at Apache :) https://www.apache.org/legal/resolved.html

I agree with @ai. MIT is compatible with/subset of CC-BY (ie: less conditions) so I don't see it as a breaking change.

**Comment by szdc** [comment]
+support for MIT

**Comment by wbobeirne** [comment]
It looks like everyone's in agreement about this, so I made a PR for it (#9) Had the same issue as most folks here that it was making it difficult to use this in a project with license concerns, so I'd love to see this switched as well.

**Comment by chicoxyzzy** [comment]
Thanks!

**Comment by chicoxyzzy** [comment]
@ai I published new version as minor
